// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tntzfnqymqgyzcuttsyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudHpmbnF5bXFneXpjdXR0c3luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MDgzOTksImV4cCI6MjA4ODA4NDM5OX0.hX8rIZzHR1k1JmiK7rXbJ1qTUTBWA7PLrkWVbNV91po";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);